version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: test_app
    working_dir: /var/www/test
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev

  db:
    image: mysql:8.0
    container_name: test_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: test_redis
    ports:
      - "6379:6379"

volumes:
  dbdata:
